# Generated by Django 4.2.4 on 2023-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_author_confirmed_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='confirmed',
        ),
    ]
