"""models update

Revision ID: c000fd60ced7
Revises: c522c6606e45
Create Date: 2023-08-01 08:19:58.594053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c000fd60ced7'
down_revision = 'c522c6606e45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('contacts', 'surname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password')
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('contacts', 'surname',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
